apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-api-ingress
  namespace: nexus
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: api.nexus.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexus-api
                port:
                  number: 8000
